# StockIQ — Sponsorship & Funding
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Mamun]
ko_fi: stockiq
open_collective: stockiq
custom:
  - https://buymeacoffee.com/stockiq
  - https://opencollective.com/stockiq
